# Generated by Django 3.0.8 on 2020-07-19 19:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.CharField(max_length=45)),
                ('informacionmedica', models.CharField(max_length=500)),
                ('fecha', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=60, unique=True)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TipoExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texamen', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('examen', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ficha.Examen')),
                ('receta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ficha.Receta')),
            ],
        ),
        migrations.AddField(
            model_name='examen',
            name='tipoexamen',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ficha.TipoExamen'),
        ),
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=100)),
                ('diagnostico', models.CharField(max_length=200)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('doctor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rut', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente')),
                ('tratamiento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ficha.Tratamiento')),
            ],
            managers=[
                ('fichas', django.db.models.manager.Manager()),
            ],
        ),
    ]
