# Generated by Django 3.1.3 on 2020-11-04 04:39

import API.Validacion_de_Run
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.CharField(max_length=45)),
                ('informacionmedica', models.CharField(max_length=500)),
                ('fecha', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10, unique=True, validators=[API.Validacion_de_Run.verificador_run])),
                ('nombre', models.CharField(max_length=45)),
                ('apellidoP', models.CharField(max_length=45)),
                ('apellidoM', models.CharField(max_length=45)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=60)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
            ],
            managers=[
                ('pacientes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=60, unique=True)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TipoExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texamen', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('rut', models.CharField(max_length=10, unique=True, validators=[API.Validacion_de_Run.verificador_run])),
                ('nombre', models.CharField(max_length=45)),
                ('apellidoP', models.CharField(max_length=45)),
                ('apellidoM', models.CharField(max_length=45)),
                ('especialidad', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('examen', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.examen')),
                ('receta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.receta')),
            ],
        ),
        migrations.AddField(
            model_name='examen',
            name='tipoexamen',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.tipoexamen'),
        ),
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=100)),
                ('diagnostico', models.CharField(max_length=200)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('doctor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rut', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.paciente')),
                ('tratamiento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.tratamiento')),
            ],
            managers=[
                ('fichas', django.db.models.manager.Manager()),
            ],
        ),
    ]
